name: Build Typst document
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Typst Compiler
          # You may pin to the exact commit or the version.
          # uses: ammar-ahmed22/compile-typst-action@7e840aaaeacb7f3f4b6724776148f65a0d4aab04
        uses: ammar-ahmed22/compile-typst-action@v1.0.2
        with:
          # Space separated list of paths to the .typ files
          source_paths: src/thesis.typ
          # Space separated list of output paths (must be .pdf) (defaults to the same name as the source_paths)
          output_paths: thesis.pdf
      - name: Upload files to a GitHub release
        # You may pin to the exact commit or the version.
        # uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd
        uses: svenstaro/upload-release-action@2.9.0
        with:
          # Local file to upload.
          file:  thesis.pdf
          # Tag to use as a release.
          prerelease: "false"
          # Mark the release the latest release for the repository. Defaults to "true".